### ISSUE TITLE
ModuleNotFoundError: No module named 'tf'

### ISSUE THREAD

**Issue by woodcore-an** [FLW-TUDO/3d_annotation_tool#1]
Hi~
Thanks for your sharing.
when i run `python tool-gui.py`, it has the following problems:
```
Traceback (most recent call last):
  File "tool-gui.py", line 11, in <module>
    from tf.transformations import quaternion_matrix
ModuleNotFoundError: No module named 'tf'
```

Can you share the requirement.txt? And python2 or python3.

**Comment by woodcore-an** [comment]
Is this tool manual or semi manual? That is, mark a picture, and the following pictures can get the corresponding pose?

**Comment by AnasIbrahim** [comment]
I deleted this module already

**Comment by woodcore-an** [comment]
I saw it, thanks~
