### ISSUE TITLE
Data organization of /path/to/dataset

### ISSUE THREAD

**Issue by jc0725** [FLW-TUDO/3d_annotation_tool#3]
Thank you very much for sharing your work. I have seen your work on the bop_toolkit. I am quite new to this field and am looking for some help.

Would you tell me how I should organize my dataset for this tool to work? I am getting the following error: Could not find scene or object meshes folder

I have changed the file path in [https://github.com/thodan/bop_toolkit/blob/9c44184631e294281c41c011e7fa1027a891bf69/scripts/annotation_tool.py#L28)](https://github.com/thodan/bop_toolkit/blob/9c44184631e294281c41c011e7fa1027a891bf69/scripts/annotation_tool.py#L28)

Currently I am trying to annotate one object using two different photos. 
My dataset is currently organized in the following way:

dataset_to_annotate/
..data/
......01/
..........depth/
..............0000.png
..............0001.png
..........rgb/
..............0000.png
..............0001.png
..models/
......obj_01.ply

Thank you in advance!

**Comment by AnasIbrahim** [comment]
The data should be organized as specified by the [BOP format](https://github.com/thodan/bop_toolkit/blob/master/docs/bop_datasets_format.md). You also can take a look at other datasets with [the same format](https://bop.felk.cvut.cz/datasets/) as an example.
What I notice is different in your data structure is that all numbers in BOP format are 6 digits. So the correct format is:
```
dataset_to_annotate/
..data/  --> better make it "train", "test", "train_my" or so
......000001/
..........depth/
..............000000.png
..............000001.png
..........rgb/
..............000000.png
..............000001.png
..models/
......obj_000001.ply
```

**Comment by jc0725** [comment]
@AnasIbrahim 
Thank you very much for your response.
