### ISSUE TITLE
Custom dataset

### ISSUE THREAD

**Issue by jc0725** [FLW-TUDO/3d_annotation_tool#4]
Hello. 
How have you managed to create your own DoPose dataset?

When I use my 3d camera to acquire data, the output depth image is in .exr format. 
My understanding is that it needs to be converted to unsigned 16-bit grayscale.
How have you managed to format your own depth data?

I tried converting the .exr format, and the only format I could manage was 1-bit grayscale.
When I used it to run the annotation tool you have kindly provided, the GUI only gave me a 2D scene instead of a 3D scene.

Thank you very much.

**Comment by AnasIbrahim** [comment]
The data must be in the [BOP format](https://github.com/thodan/bop_toolkit/blob/master/docs/bop_datasets_format.md).

So converting the depth image to png is correct. Maybe you have something wrong with your conversion. What method or library are you using for this conversion? Can you give me more info so I can help you? I think there should be a way to somehow specify the output format of the png then the tool should work fine.

**Comment by jc0725** [comment]
Thank you for your response.

I tried converting the file using [ImageMagick](https://imagemagick.org/index.php).
I ran two command lines (I was thinking that the first command was enough, but it wasn't so I ran it again): 
1. convert **depth.exr** -depth 16 -colorspace Grey **depth.png** 
   [this outputted file type of 16-bit/color RGBA]
2. convert **depth.png** -depth 16 -colorspace Grey **newdepth.png** 
   [this outputted file type of 1-bit grayscale]

Currently, I am using a RGBD camera that only outputs .exr depth files.
However, I may have access to RealSense in the near future. Do you know if RealSense may work better?

**Comment by jc0725** [comment]
@AnasIbrahim 
Hello again.
I was able to convert the file to 16bit png.  The following is my depth file type:
`PNG image data, 1440 x 1080, 16-bit grayscale, non-interlaced`
However, when I run your annotation tool, I only get a 2D scene instead of a 3D scene.
Would you have any idea why this is happening?


FYI, the following is the code I ran to convert .exr to .png:
> filename='depth.exr' 
output_filename='depth.png'
im=cv2.imread(filename, IMREAD_GRAYSCALE)
im=np.uint16(im)
cv2.imwrite('output_filename',im)

Thank you.

**Comment by AnasIbrahim** [comment]
make sure your depth values are in mm and not in meters.

**Comment by jc0725** [comment]
Would that change be accomplished by changing the depth_scale value in scene_camera.json? 
Thank you, and I apologize for the elementary questions.

**Comment by AnasIbrahim** [comment]
Yes setting the depth_scale would solve the problem. If that's the only problem with the depth image format.
